### ISSUE TITLE
test page prompts for access to private cloudant DB

### ISSUE THREAD

**Issue by dch** [cloudant-labs/backbone.cloudant#1]
Hi Simon,

Nice work - awesome!

This is likely cosmetic, but I can't see directly what's causing this?

```
A user name and password are being requested by https://drsm79.cloudant.com. The site says: "Cloudant Private Database"
```

**Comment by drsm79** [comment]
Hey Dave, 
The test page does a write every 10s (to test writes) but I've not opened the database to world writes. There's a todo in the code to improve how authentication is handled, there are a few options I want to experiment with. 
Thanks for taking the time to report it.
Simon
