### ISSUE TITLE
here's a patch for eliminating an error when the response doesn't have the 'rows' attribute

### ISSUE THREAD

**Issue by rbpasker** [cloudant-labs/backbone.cloudant#6]
if you manage to query the root document of a database, you don't get any rows in the Collection. 

this patch fakes an empty set of rows, rather than generating a console error.

@@ -125,6 +125,11 @@ Backbone.Cloudant.Collection = Backbone.Collection.extend({
   // Server queries return metadata as well as the documents in the collection
   // deal with that here.
   parse: function(response){
-    if (response.rows) {
-   response.rows = "[]"; // pretend its an empty response
-    }
  +
  +
   if (response.total_rows) {
     this.totalLength = response.total_rows;
   } else {
  @@ -238,4 +243,4 @@ Backbone.Cloudant.View = {
     return [Backbone.Cloudant.database, "_design", this.design, "_view", this.view].join("/");
   }
  })
  -};
  \ No newline at end of file
  +};

**Comment by rbpasker** [comment]
this doesn't work. the problem still exists, but the proposed patch broke other code

**Comment by drsm79** [comment]
Thanks for closing it :)
